/**
 * Single source of truth for medical specialties across the entire platform.
 * Import SPECIALTIES_FILTER for filter UIs (includes "Todas") or
 * SPECIALTIES_LIST for selection dropdowns (includes "Otra especialidad").
 */

export const SPECIALTIES_FILTER = [
  { value: 'Todas', labelKey: 'doctors.specAll' },
  { value: 'Alergología e Inmunología', labelKey: 'doctors.specAllergology' },
  { value: 'Algología', labelKey: 'doctors.specAlgology' },
  { value: 'Anestesiología', labelKey: 'doctors.specAnesthesiology' },
  { value: 'Anestesiología Pediátrica', labelKey: 'doctors.specPediatricAnesthesiology' },
  { value: 'Angiología, Cirugía Vascular y Endovascular', labelKey: 'doctors.specAngiology' },
  { value: 'Biología de la Reproducción Humana', labelKey: 'doctors.specReproductiveBiology' },
  { value: 'Broncoscopía Intervencionista', labelKey: 'doctors.specBronchoscopy' },
  { value: 'Cardiología Clínica', labelKey: 'doctors.specClinicalCardiology' },
  { value: 'Cardiología Intervencionista', labelKey: 'doctors.specInterventionalCardiology' },
  { value: 'Cardiología Intervencionista en Cardiopatías Congénitas', labelKey: 'doctors.specInterventionalCardiologyCongenital' },
  { value: 'Cardiología Intervencionista Pediátrica', labelKey: 'doctors.specPediatricInterventionalCardiology' },
  { value: 'Cardiología Pediátrica', labelKey: 'doctors.specPediatricCardiology' },
  { value: 'Cirugía Bariátrica', labelKey: 'doctors.specBariatricSurgery' },
  { value: 'Cirugía Cardíaca', labelKey: 'doctors.specCardiacSurgery' },
  { value: 'Cirugía Cardíaca Pediátrica', labelKey: 'doctors.specPediatricCardiacSurgery' },
  { value: 'Cirugía Cardiotorácica', labelKey: 'doctors.specCardiothoracicSurgery' },
  { value: 'Cirugía de Colon y Recto', labelKey: 'doctors.specColorectalSurgery' },
  { value: 'Cirugía de Tórax', labelKey: 'doctors.specThoracicSurgery' },
  { value: 'Cirugía de Tórax Pediátrica', labelKey: 'doctors.specPediatricThoracicSurgery' },
  { value: 'Cirugía de Trasplantes', labelKey: 'doctors.specTransplantSurgery' },
  { value: 'Cirugía del Aparato Digestivo', labelKey: 'doctors.specDigestiveSurgery' },
  { value: 'Cirugía General', labelKey: 'doctors.specGeneralSurgery' },
  { value: 'Cirugía Maxilofacial', labelKey: 'doctors.specMaxillofacialSurgery' },
  { value: 'Cirugía Oncológica', labelKey: 'doctors.specOncologicalSurgery' },
  { value: 'Cirugía Oncológica Pediátrica', labelKey: 'doctors.specPediatricOncologicalSurgery' },
  { value: 'Cirugía Pediátrica', labelKey: 'doctors.specPediatricSurgery' },
  { value: 'Cirugía Plástica, Estética y Reconstructiva', labelKey: 'doctors.specPlasticSurgery' },
  { value: 'Cirugía Torácica No Cardiaca', labelKey: 'doctors.specNonCardiacThoracicSurgery' },
  { value: 'Coloproctología', labelKey: 'doctors.specColoproctology' },
  { value: 'Comunicación, Audiología, Otoneurología y Foniatría', labelKey: 'doctors.specAudiologyPhoniatrics' },
  { value: 'Cuidados Paliativos', labelKey: 'doctors.specPalliativeCare' },
  { value: 'Dermatología', labelKey: 'doctors.specDermatology' },
  { value: 'Dermatología Pediátrica', labelKey: 'doctors.specPediatricDermatology' },
  { value: 'Ecocardiografía Adultos', labelKey: 'doctors.specAdultEchocardiography' },
  { value: 'Ecocardiografía Pediátrica', labelKey: 'doctors.specPediatricEchocardiography' },
  { value: 'Electrofisiología', labelKey: 'doctors.specElectrophysiology' },
  { value: 'Endocrinología', labelKey: 'doctors.specEndocrinology' },
  { value: 'Endocrinología Pediátrica', labelKey: 'doctors.specPediatricEndocrinology' },
  { value: 'Endoscopía', labelKey: 'doctors.specEndoscopy' },
  { value: 'Endoscopia Gastrointestinal', labelKey: 'doctors.specGIEndoscopy' },
  { value: 'Endoscopía Torácica', labelKey: 'doctors.specThoracicEndoscopy' },
  { value: 'Gastroenterología', labelKey: 'doctors.specGastroenterology' },
  { value: 'Gastroenterología Pediátrica', labelKey: 'doctors.specPediatricGastroenterology' },
  { value: 'Genética Médica', labelKey: 'doctors.specMedicalGenetics' },
  { value: 'Geriatría', labelKey: 'doctors.specGeriatrics' },
  { value: 'Ginecología Oncológica', labelKey: 'doctors.specGynecologicalOncology' },
  { value: 'Ginecología y Obstetricia', labelKey: 'doctors.specGynecology' },
  { value: 'Hematología', labelKey: 'doctors.specHematology' },
  { value: 'Hematología Pediátrica', labelKey: 'doctors.specPediatricHematology' },
  { value: 'Imagen de la Mama', labelKey: 'doctors.specBreastImaging' },
  { value: 'Imagen del Sistema Musculoesquelético', labelKey: 'doctors.specMSKImaging' },
  { value: 'Infectología', labelKey: 'doctors.specInfectology' },
  { value: 'Infectología Pediátrica', labelKey: 'doctors.specPediatricInfectology' },
  { value: 'Medicina Crítica', labelKey: 'doctors.specCriticalCare' },
  { value: 'Medicina de Rehabilitación', labelKey: 'doctors.specRehabMedicine' },
  { value: 'Medicina del Enfermo Pediátrico Cardiovascular en Estado Crítico', labelKey: 'doctors.specPedCriticalCardio' },
  { value: 'Medicina del Enfermo Pediátrico en Estado Crítico', labelKey: 'doctors.specPedCriticalCare' },
  { value: 'Medicina del Sueño', labelKey: 'doctors.specSleepMedicine' },
  { value: 'Medicina General', labelKey: 'doctors.specGeneralMedicine' },
  { value: 'Medicina Interna', labelKey: 'doctors.specInternalMedicine' },
  { value: 'Medicina Materna Fetal', labelKey: 'doctors.specMaternalFetalMedicine' },
  { value: 'Medicina Nuclear', labelKey: 'doctors.specNuclearMedicine' },
  { value: 'Medicina Nuclear Cardiológica', labelKey: 'doctors.specCardiacNuclearMedicine' },
  { value: 'Medicina Nuclear Oncológica Molecular y Terapéutica', labelKey: 'doctors.specOncologicNuclearMedicine' },
  { value: 'Médico Cirujano', labelKey: 'doctors.specGeneralPractitioner' },
  { value: 'Nefrología', labelKey: 'doctors.specNephrology' },
  { value: 'Nefrología Pediátrica', labelKey: 'doctors.specPediatricNephrology' },
  { value: 'Neonatología', labelKey: 'doctors.specNeonatology' },
  { value: 'Neumología', labelKey: 'doctors.specPulmonology' },
  { value: 'Neumología Pediátrica', labelKey: 'doctors.specPediatricPulmonology' },
  { value: 'Neuroanestesiología', labelKey: 'doctors.specNeuroanesthesiology' },
  { value: 'Neurocirugía', labelKey: 'doctors.specNeurosurgery' },
  { value: 'Neurocirugía Pediátrica', labelKey: 'doctors.specPediatricNeurosurgery' },
  { value: 'Neurofisiología Clínica', labelKey: 'doctors.specClinicalNeurophysiology' },
  { value: 'Neurolingüística', labelKey: 'doctors.specNeurolinguistics' },
  { value: 'Neurología', labelKey: 'doctors.specNeurology' },
  { value: 'Neurología Pediátrica', labelKey: 'doctors.specPediatricNeurology' },
  { value: 'Neurootología', labelKey: 'doctors.specNeurootology' },
  { value: 'Neurorradiología', labelKey: 'doctors.specNeuroradiology' },
  { value: 'Nutrición Clínica', labelKey: 'doctors.specClinicalNutrition' },
  { value: 'Nutrición de Alimentos', labelKey: 'doctors.specFoodNutrition' },
  { value: 'Nutrición y Ciencias de los Alimentos', labelKey: 'doctors.specNutritionScience' },
  { value: 'Nutrición', labelKey: 'doctors.specNutrition' },
  { value: 'Odontología', labelKey: 'doctors.specDentistry' },
  { value: 'Odontología Pediátrica', labelKey: 'doctors.specPediatricDentistry' },
  { value: 'Oftalmología', labelKey: 'doctors.specOphthalmology' },
  { value: 'Oncología Médica', labelKey: 'doctors.specMedicalOncology' },
  { value: 'Oncología Pediátrica', labelKey: 'doctors.specPediatricOncology' },
  { value: 'Ortopedia y Traumatología', labelKey: 'doctors.specOrthopedics' },
  { value: 'Otorrinolaringología Pediátrica', labelKey: 'doctors.specPediatricENT' },
  { value: 'Otorrinolaringología y Cirugía de Cabeza y Cuello', labelKey: 'doctors.specENT' },
  { value: 'Patología Clínica', labelKey: 'doctors.specClinicalPathology' },
  { value: 'Patología Quirúrgica', labelKey: 'doctors.specSurgicalPathology' },
  { value: 'Pediatría', labelKey: 'doctors.specPediatrics' },
  { value: 'Proctología', labelKey: 'doctors.specProctology' },
  { value: 'Psicología', labelKey: 'doctors.specPsychology' },
  { value: 'Psiquiatría Adultos', labelKey: 'doctors.specAdultPsychiatry' },
  { value: 'Psiquiatría Infantil y de la Adolescencia', labelKey: 'doctors.specChildPsychiatry' },
  { value: 'Radio-Oncología', labelKey: 'doctors.specRadiationOncology' },
  { value: 'Radiología e Imagen', labelKey: 'doctors.specRadiology' },
  { value: 'Radiología Vascular e Intervencionista', labelKey: 'doctors.specVascularRadiology' },
  { value: 'Rehabilitación Cardíaca y Prevención Secundaria', labelKey: 'doctors.specCardiacRehab' },
  { value: 'Rehabilitación Oncológica', labelKey: 'doctors.specOncologicRehab' },
  { value: 'Reumatología', labelKey: 'doctors.specRheumatology' },
  { value: 'Reumatología Pediátrica', labelKey: 'doctors.specPediatricRheumatology' },
  { value: 'Terapia Endovascular Neurológica', labelKey: 'doctors.specNeuroEndovascular' },
  { value: 'Terapia Física y Rehabilitación', labelKey: 'doctors.specPhysicalTherapy' },
  { value: 'Urgencias', labelKey: 'doctors.specEmergencyMedicine' },
  { value: 'Urgencias Pediátricas', labelKey: 'doctors.specPediatricEmergency' },
  { value: 'Urología', labelKey: 'doctors.specUrology' },
  { value: 'Urología Ginecológica', labelKey: 'doctors.specGynecologicalUrology' },
] as const;

/** Plain string array for dropdowns (onboarding, live setup, meetings, clinical sessions). Includes "Otra especialidad" at the end. */
export const SPECIALTIES_LIST: string[] = [
  ...SPECIALTIES_FILTER.filter(s => s.value !== 'Todas').map(s => s.value),
  'Otra especialidad',
];
