project_id = "jbthjpnxiwnegzgfzfth"

[functions.create-daily-room]
verify_jwt = false

[functions.end-daily-room]
verify_jwt = false

[functions.get-daily-token]
verify_jwt = false

[functions.daily-webhook]
verify_jwt = false

[functions.purchase-recording-wallet]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false